defaults:
  # Hydra's launcher API is synchronous and not async https://github.com/facebookresearch/hydra/issues/1377#issuecomment-773583397 so all jobs in a batch must finish before launching next batch
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 115 # 2 hours
tasks_per_node: 1
nodes: 1
name: ${hydra.job.name}
comment: null
exclude: null
signal_delay_s: 600
max_num_timeout: 20
additional_parameters: {}
array_parallelism: 4
setup: 
  - module --quiet purge
  - module load cudatoolkit/12.1
  - module load miniconda/3
  - conda activate roble
  - unset CUDA_VISIBLE_DEVICES
mem_gb: 32
gres: gpu:a100