defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: grp-64-h-optim-TXT-multi-class
    storage: null
    n_trials: 6
    n_jobs: 2
    params:
      batch_size: choice(128)
      gradient_accumulation_steps: choice(1, 2, 4)
  
batch_size: 128 # how many independent sequences will we process in parallel?
block_size: 32 ## Will be overidden by code
vocab_size: 32 ## Will be overidden by code
n_patches: 8
max_iters: 20000
eval_interval: 100
learning_rate: 5e-5
eval_iters: 200
n_embd: 256
device: "cpu"
testing: true
simEval: false
gradient_accumulation_steps: 4
# ------------

r_seed: 1337
n_head: 16
n_blocks: 4
dropout: 0.2
action_bins: 10
action_dim: 6

## Model hyperparameters
image_shape: [64, 64, 3]
dataset: gberseth/mini-bridge-mini64px
trim: 1000000

# if true, simulate a failure by raising an exception
error: false