defaults:
  - override hydra/launcher: MY_2HRS
  - _self_

experiment:
  name: my_mini_grp_experiment 
  
batch_size: 128 # how many independent sequences will we process in parallel?
block_size: 32 ## Will be overidden by code
vocab_size: 32 ## Will be overidden by code
n_patches: 8
max_iters: 20000
eval_interval: 100
learning_rate: 5e-5
eval_iters: 200
n_embd: 256
device: "cpu"
testing: true
simEval: false
gradient_accumulation_steps: 4

# ------------

r_seed: 1337
n_head: 16
n_blocks: 4
dropout: 0.2
action_bins: 10
action_dim: 6

## Model hyperparameters
image_shape: [64, 64, 3]
dataset: gberseth/mini-bridge-mini64px
trim: 1000000

# if true, simulate a failure by raising an exception
error: false