defaults:
  - override hydra/launcher: MY_2HRS
  - _self_


hydra:
  launcher: 
    gres: gpu:a100 # 
    # gpus-per-task: rtx8000:1
    mem_gb: 32
    tasks_per_node: 1
    cpus_per_task: 8
    array_parallelism: 3 # I think this means run per job.
    additional_parameters:
      time: 0-03:00:00                               # maximum wall time allocated for the job (D-H:MM:SS)
      # mail-type: ARRAY_TASKS,FAIL,TIME_LIMIT         # events to notify user by email
      # mail-user: ???                                 # email of the user

experiment:
  name: mini_grp
  project: mini-grp
  
batch_size: 128 # how many independent sequences will we process in parallel?
block_size: 32 ## Will be overidden by code
vocab_size: 32 ## Will be overidden by code
n_patches: 8
max_iters: 20000
eval_interval: 100
learning_rate: 5e-5
eval_iters: 200

n_embd: 512
device: "cpu"
testing: true
simEval: true
eval_vid_iters: 1000
gradient_accumulation_steps: 2

# ------------

r_seed: 1337
n_head: 16
n_blocks: 4
dropout: 0.2
action_bins: 10
action_dim: 6

## Model hyperparameters
image_shape: [64, 64, 3]
dataset: gberseth/mini-bridge-mini64px
trim: 1000000

# if true, simulate a failure by raising an exception
error: false